// Mock Clients
export const mockClients = [
  {
    id: "1",
    name: "Acme Inc",
    email: "contact@acmeinc.com",
    phone: "555-123-4567",
    activeTasks: 4,
    completedTasks: 8,
  },
  {
    id: "2",
    name: "TechCorp",
    email: "info@techcorp.com",
    phone: "555-987-6543",
    activeTasks: 3,
    completedTasks: 5,
  },
  {
    id: "3",
    name: "Design Studio",
    email: "hello@designstudio.com",
    phone: "555-456-7890",
    activeTasks: 2,
    completedTasks: 7,
  },
  {
    id: "4",
    name: "Marketing Pro",
    email: "team@marketingpro.com",
    phone: "555-789-0123",
    activeTasks: 2,
    completedTasks: 3,
  },
  {
    id: "5",
    name: "Startup Labs",
    email: "founders@startuplabs.com",
    phone: "555-321-6547",
    activeTasks: 1,
    completedTasks: 1,
  },
]

// Mock Tasks
export const mockTasks = [
  {
    id: "1",
    clientId: "1",
    title: "Website Redesign",
    description: "Redesign the company website with new branding",
    estimatedDuration: 180, // minutes
    dueDate: "2023-05-15T00:00:00.000Z",
    status: "in-progress",
  },
  {
    id: "2",
    clientId: "1",
    title: "Logo Update",
    description: "Update the logo with new color scheme",
    estimatedDuration: 90,
    dueDate: "2023-05-10T00:00:00.000Z",
    status: "todo",
  },
  {
    id: "3",
    clientId: "1",
    title: "Social Media Campaign",
    description: "Create a social media campaign for product launch",
    estimatedDuration: 120,
    dueDate: "2023-05-20T00:00:00.000Z",
    status: "todo",
  },
  {
    id: "4",
    clientId: "1",
    title: "Email Newsletter",
    description: "Design and send monthly email newsletter",
    estimatedDuration: 60,
    dueDate: "2023-05-05T00:00:00.000Z",
    status: "done",
  },
  {
    id: "5",
    clientId: "2",
    title: "Mobile App Development",
    description: "Develop a mobile app for client services",
    estimatedDuration: 240,
    dueDate: "2023-06-15T00:00:00.000Z",
    status: "in-progress",
  },
  {
    id: "6",
    clientId: "2",
    title: "API Integration",
    description: "Integrate payment gateway API",
    estimatedDuration: 120,
    dueDate: "2023-05-25T00:00:00.000Z",
    status: "todo",
  },
  {
    id: "7",
    clientId: "2",
    title: "Database Optimization",
    description: "Optimize database queries for better performance",
    estimatedDuration: 90,
    dueDate: "2023-05-12T00:00:00.000Z",
    status: "done",
  },
  {
    id: "8",
    clientId: "3",
    title: "Brand Guidelines",
    description: "Create comprehensive brand guidelines document",
    estimatedDuration: 150,
    dueDate: "2023-05-18T00:00:00.000Z",
    status: "in-progress",
  },
  {
    id: "9",
    clientId: "3",
    title: "Product Packaging",
    description: "Design new product packaging",
    estimatedDuration: 120,
    dueDate: "2023-05-30T00:00:00.000Z",
    status: "todo",
  },
  {
    id: "10",
    clientId: "3",
    title: "Marketing Materials",
    description: "Design brochures and business cards",
    estimatedDuration: 90,
    dueDate: "2023-05-08T00:00:00.000Z",
    status: "done",
  },
  {
    id: "11",
    clientId: "4",
    title: "SEO Audit",
    description: "Perform SEO audit and provide recommendations",
    estimatedDuration: 120,
    dueDate: "2023-05-22T00:00:00.000Z",
    status: "todo",
  },
  {
    id: "12",
    clientId: "4",
    title: "Content Calendar",
    description: "Create content calendar for next quarter",
    estimatedDuration: 60,
    dueDate: "2023-05-16T00:00:00.000Z",
    status: "in-progress",
  },
  {
    id: "13",
    clientId: "5",
    title: "Pitch Deck",
    description: "Create investor pitch deck",
    estimatedDuration: 180,
    dueDate: "2023-05-28T00:00:00.000Z",
    status: "todo",
  },
]

// Mock Daily Schedule
export const mockSchedule = [
  {
    taskId: "1",
    title: "Website Redesign",
    client: "Acme Inc",
    duration: 180,
    timeSlot: 0, // 8:00 AM
    locked: true,
  },
  {
    taskId: "5",
    title: "Mobile App Development",
    client: "TechCorp",
    duration: 120,
    timeSlot: 6, // 11:00 AM
    locked: false,
  },
  {
    taskId: "8",
    title: "Brand Guidelines",
    client: "Design Studio",
    duration: 90,
    timeSlot: 10, // 1:00 PM
    locked: false,
  },
  {
    taskId: "12",
    title: "Content Calendar",
    client: "Marketing Pro",
    duration: 60,
    timeSlot: 14, // 3:00 PM
    locked: true,
  },
]
